runtime: nodejs18

instance_class: F1

handlers:
  - url: /(.*\..+)$
    secure: always
    static_files: apps/website/dist/\1
    upload: apps/website/dist/(.*\..+)$
    # catch all handler to index.html
  - url: /.*
    secure: always
    static_files: apps/website/dist/index.html
    upload: apps/website/dist/index.html
