name: Publish to Azure App Services

concurrency:
  group: develop
  cancel-in-progress: true

on:
  push:
    branches:
      - 'develop'
    paths:
      - "apps/**"
      - "libs/**"
      - ".github/workflows/publish_to_develop.yml"

jobs:
  publish:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Fetch secrets
        env:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}
        run: echo "$ENV_SECRETS" > env.json

      - name: Setup secrets
        run: pnpm -w run envs

      - name: Build apps
        run: pnpm --filter ./apps/website build

      - name: Copy config
        run: cp ./staticwebapp.config.json ./apps/website/dist/staticwebapp.config.json

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: 'apps/website/dist'
          output_location: ''
          skip_app_build: true
          deployment_environment: Production