name: Publish to Azure App Services on PR

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - "src/**"
      - ".github/workflows/publish_on_pr.yml"

jobs:
  publish:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Web Deployment
        uses: ./.github/actions/web-deploy
        with:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: 'dist'
          output_location: ''
          skip_app_build: true

  clean_deployed_environment:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN }}
          action: "close"