name: Publish to Azure App Services

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - 'production'
    paths:
      - "src/**"
      - ".github/workflows/publish_to_production.yml"

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Web Deployment
        uses: ./.github/actions/web-deploy
        with:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: 'dist'
          output_location: ''
          skip_app_build: true